version: '3.8'

services:

  endpoint:
    build:
      context: ./endpoint
      dockerfile: endpoint.Dockerfile
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    restart: on-failure
    env_file:
      - env_vars
    networks:
      - inner
    depends_on:
      - worker-endpoint
  
  worker-endpoint:
    build:
      context: ./endpoint
      dockerfile: worker.Dockerfile
    command: celery -A tasks worker -l INFO
    restart: on-failure
    env_file:
      - env_vars
    networks:
      - inner
    depends_on:
      - redis
      - rabbitmq

  consumer:
    build:
      context: ./consumer
      dockerfile: consumer.Dockerfile
    command: python -u main.py
    restart: on-failure
    env_file:
      - env_vars
    networks:
      - inner
    depends_on:
      - rabbitmq
      - redis
      - worker-consumer

  worker-consumer:
    build:
      context: ./consumer
      dockerfile: worker.Dockerfile
    command: celery -A tasks worker -l INFO
    restart: on-failure
    env_file:
      - env_vars
    networks:
      - inner
    depends_on:
      - rabbitmq
      - mariadb

  rabbitmq:
    image: rabbitmq:3-alpine
    environment:
        - RABBITMQ_DEFAULT_VHOST=my_vhost
        - RABBITMQ_DEFAULT_USER=rabbit
        - RABBITMQ_DEFAULT_PASS=QweZxc123
    #ports:
    #    - 5672:5672
    networks:
        - inner
    volumes:
        - ./.env/rabbit/data/:/var/lib/rabbitmq/
  
  redis:
    image: redis:6.2-alpine
    restart: on-failure
    #ports:
    #  - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass QweZxc123
    networks:
      - inner
    volumes: 
      - ./.env/redis-broker/data/:/data
  
  mariadb:
    image: mariadb:10.7
    restart: on-failure
    #ports:
    #  - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: QweZxc123
      MARIADB_DATABASE: ukcodes
    volumes:
      - ./.env/mariadb/data:/var/lib/mysql
    networks:
      - inner

networks:
  inner:
    driver: bridge
