version: '3.8'

services:

  endpoint:
    build:
      context: ./endpoint
      dockerfile: endpoint.Dockerfile
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_VHOST=my_vhost
      - RABBIT_QUEUE=coordinates_to_process
      - REDIS_HOST=redis-broker
      - REDIS_PORT=6379
      - REDIS_PASSWORD=QweZxc123
      - REDIS_DB=0
    networks:
      - inner
    depends_on:
      - worker-endpoint
  
  worker-endpoint:
    build:
      context: ./endpoint
      dockerfile: worker.Dockerfile
    command: celery -A tasks worker -l INFO
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_VHOST=my_vhost
      - RABBIT_QUEUE=coordinates_to_process
      - REDIS_HOST=redis-broker
      - REDIS_PORT=6379
      - REDIS_PASSWORD=QweZxc123
      - REDIS_DB=0
    networks:
      - inner
    depends_on:
      - redis-broker
      - rabbitmq

  consumer:
    build:
      context: ./consumer
      dockerfile: consumer.Dockerfile
    command: python -u main.py
    restart: on-failure
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_VHOST=my_vhost
      - RABBIT_QUEUE=coordinates_to_process
    networks:
      - inner
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-alpine
    environment:
        - RABBITMQ_DEFAULT_VHOST=my_vhost
    ports:
        - 5672:5672
    networks:
        - inner
    volumes:
        - ./.env/rabbit/data/:/var/lib/rabbitmq/
        - ./.env/rabbit/log/:/var/log/rabbitmq/
  
  redis-broker:
    image: redis:6.2-alpine
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass QweZxc123
    networks:
      - inner
    volumes: 
      - ./.env/redis-broker/data/:/data

networks:
  inner:
    driver: bridge
