version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
        - RABBITMQ_DEFAULT_VHOST=my_vhost
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./.env/rabbit/data/:/var/lib/rabbitmq/
        - ./.env/rabbit/log/:/var/log/rabbitmq/
    networks:
        - inner
  
  redis-broker:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./.env/redis-broker/data/:/data

networks:
  inner:
    driver: bridge
