version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
        - RABBITMQ_DEFAULT_VHOST=my_vhost
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./.env/rabbit/data/:/var/lib/rabbitmq/
        - ./.env/rabbit/log/:/var/log/rabbitmq/
    networks:
        - inner

networks:
  inner:
    driver: bridge
